### ISSUE TITLE
Demo video not available

### ISSUE THREAD

**Issue by abdoei** [gabrielcdb/RealJarvis#1]
Following the link in the Readme below it gaves me `Sorry. Unless you've got a time machine, that content is unavailable.` on twitch.
```md
🎬 Demonstration
https://www.twitch.tv/videos/1861765919
```

**Comment by gabrielcdb** [comment]
Hi,

Since it was a twitch vidéo it got discontinued. I'll upload it on YouTube,
soon or later. Know that this project is not up to date since the chatgpt
api changed a lot since this github last update.

Regards,

Gabrielcdb

**Comment by abdoei** [comment]
Ah ok, thank you for clarifying this. I will be the first to view the YT video tho. please consider mentioning the state of the repo on the readme or even make it archived.

**Comment by gabrielcdb** [comment]
Okay so I resumed the video on twitch and added a title indicating the
project is not supported anymore.

If you are interested in taking the project a step further tell me. I have
plenty of idea but I lack of time.

**Comment by abdoei** [comment]
I saw the video and it is a nice app. I think I don't have room for this nice project in my schedule as I am working on my grad project which happens to be an Arabic-efficient ASR model.

**Comment by gabrielcdb** [comment]
Well, at first for my grad project I was working on doing the same with
french but because openai made Whisper a free tool , and the current best
ASR ever made, I shifted from pure ASR research to ASR application.
I don't know Whisper performance on arabic though, so
I wish you the best of luck on this very tricky problem. Feel free to let
me know if you managed to get better results than open ai labs, it would be
awesome! Now I wonder if you could build a fine tuning system for whisper
actually 🤔

Remember, All you need is attention, and a petabyte of labelled audio data
😂

**Comment by abdoei** [comment]
What a surprise :). Whisper is good at Arabic too but Arabic is not what people record on YT or social media, we all use slang. So it is not correct by design if I can say so 😂. We are tuning it on the scriptures of the Holy Quran as it is the standard Arabic both in pronunciation and writing.
I will inform you if we can get any performance at the end but we, as you probably encountered from your reactions :), are not able to find the open source code for training the model by openai so we are doing basic backpropagation but just on Arabic, that is how we train it for now and managed to lower the WER a little but still searching our way to use LoRA instead.
BTW you can keep track of the reports [here](https://github.com/ElGarash/Al-Ajwad) in the experiment directory
